Rename all files to sfp driver format
This commit guaranteed does not work.
In order to make a clean history I have not updated the scripts fully,
the coming commits will fix this.

diff --git a/bin/sfp b/bin/sfp
--- a/bin/sfp
+++ b/bin/sfp
@@ -1,4 +1,20 @@
 #!/usr/bin/env bash
+# sfp
+# The front-end for shufflepaper
+#  Copyright (C) 2019 Bujiraso
+
+#  This program is free software: you can redistribute it and/or modify
+#  it under the terms of the GNU General Public License as published by
+#  the Free Software Foundation, either version 3 of the License, or
+#  any later version.
+
+#  This program is distributed in the hope that it will be useful,
+#  but WITHOUT ANY WARRANTY; without even the implied warranty of
+#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#  GNU General Public License for more details.
+
+#  You should have received a copy of the GNU General Public License
+#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 function dbug(){
     if [[ ! -z ${SFP_DEBUG+x} ]]; then
@@ -11,29 +27,41 @@ function commands_help(){
 Usage: $(basename "${0}") COMMAND
 
 Available commands are:
-    change-wall
+    $(ls -1 sfp-* | tr -d '\n\r' | sed 's/sfp-/, /g;s/^, //')
 EOS
 }
 
-# Verify subcommand is present or print commands_help
-if [[ ${#} -eq 0 ]]; then
-   commands_help
-   return 2
+# Assert that sfp can be called by subcommands
+if ! which sfp 2> /dev/null > /dev/null; then
+    sourceDir="$(dirname "$(readlink -f "${0}")")"
+    if [[ ! -d "${sourceDir}" ]]; then
+        echo "Cannot find sfp's source dir to execute subcommands through. Try installing sfp to your path" > /dev/stderr
+        exit 1
+    fi
+    export PATH="${PATH}:${sourceDir}"
 fi
 
+# Verify subcommand is present or print commands_help
+if [[ ${#} -eq 0 ]]; then
+    commands_help
+    exit 2
+fi
+
+# Set up sfp script source 
+dbug "User asked for ${command}"
+command="sfp-$(echo ${1} | sed 's/ /-/g')"
 # Shift to remove subcommand from its own args
-command="${1}"
 shift
 
-case "${command}" in
-    "change-wall")
-        source changeBG.sh
-        sfp-change-wall "${*}"
-        ;;
-    *)
-        echo "Invalid command ${command}"
-        return 3
-        ;;
-esac
+if ! which "${command}" >/dev/null 2>/dev/null; then
+    echo "Invalid command ${command}" > /dev/stderr
+    exit 3
+fi
+
+# Source script and run its main function
+dbug "Running ${command}"
+
+source "${command}"
+${command} "${*}"
 
 dbug "Exiting sfp"
diff --git a/bin/sfp-alter b/bin/sfp-alter
--- a/bin/sfp-alter
+++ b/bin/sfp-alter
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
-# updateWallInDB.sh
+# sfp-alter
 # Updates various modifiable aspects of a wallpaper in the shufflepaper database
-#  Copyright (C) 2015 - 2017 Bujiraso
+#  Copyright (C) 2015 - 2019 Bujiraso
 
 #  This program is free software: you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
@@ -16,10 +16,9 @@
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-me=$(basename "${0}")
-myDir="$(dirname "$(readlink -f "${0}")")"
-source "${myDir}/../conf/shufflepaper.conf"
-wallURI=$("${myDir}/getWallURI.sh")
+me="alter"
+source "${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf"
+wallURI=$(sfp get-uri)
 
 # The file needs to be asserted first, out of all the arguments
 count=1
@@ -39,7 +38,7 @@ while [[ "${count}" -le "${#}" ]]; do
 done
 
 #Get inode so that if /anything/ else changes we can still update
-inode=$("${myDir}/wallStats.sh" -n -f "${wallURI}" | cut -d ' ' -f 1)
+inode=$(sfp wall-stats -n -f "${wallURI}" | cut -d ' ' -f 1)
 
 if [[ "${#}" -ne 0 && -z "${inode}" ]]; then
     echo "${me}: Fatal error: no inode found for ${wallURI}" >&2
@@ -70,16 +69,16 @@ while getopts ":a:c:df:hm:p:s:t:u:v:" opt; do
            sqlChanges="${sqlChanges}"" user_comments = \"${comments}\","
            ;;
         "d")
-           dims=($("${myDir}/wallDims.sh" -n -f "${wallURI}"))
-           if [[ ${dims[0]} -eq 0 || ${dims[1]} -eq 0 ]]; then
-               echo "${me}: Cannot get dimensions for ${wallURI}." >&2
-               exit 6
-           fi
-           sqlChanges="${sqlChanges}"" width = ${dims[0]}, height = ${dims[1]},"
-           ;;
+            dims=($(sfp wall-dims -n -f "${wallURI}"))
+            if [[ ${dims[0]} -eq 0 || ${dims[1]} -eq 0 ]]; then
+                echo "${me}: Cannot get dimensions for ${wallURI}." >&2
+                exit 6
+            fi
+            sqlChanges="${sqlChanges}"" width = ${dims[0]}, height = ${dims[1]},"
+            ;;
         "h")
-           cat<<EOS
-Usage: ${me} OPTIONS...
+            cat <<EOS
+Usage: sfp ${me} OPTIONS...
 
 Options
   -a           Add user comment (appends comma, then argument)
