Modify scripts to sfp driver compatible format

diff --git a/bin/sfp-alter b/bin/sfp-alter
--- a/bin/sfp-alter
+++ b/bin/sfp-alter
@@ -16,69 +16,11 @@
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-me="alter"
-source "${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf"
-wallURI=$(sfp get-uri)
+subName="alter"
 
-# The file needs to be asserted first, out of all the arguments
-count=1
-while [[ "${count}" -le "${#}" ]]; do
-    if [[ "${!count}" == "-f" ]]; then
-      # Check that the wall file is not being set multiple times
-      if [[ -z "${set}" ]]; then
-          set=true
-          count=$((count+1))
-          wallURI=${!count}
-      else
-          echo "${me}: Wall file cannot be set twice." >&2
-          exit 3
-      fi
-    fi
-    count=$((count + 1))
-done
-
-#Get inode so that if /anything/ else changes we can still update
-inode=$(sfp wall-stats -n -f "${wallURI}" | cut -d ' ' -f 1)
-
-if [[ "${#}" -ne 0 && -z "${inode}" ]]; then
-    echo "${me}: Fatal error: no inode found for ${wallURI}" >&2
-    exit 4
-fi
-
-# If the file path is currently wrong, find the file by inode
-if [[ ! -f "${wallURI}" ]]; then
-    newURI="$(find "${wallDir}" -inum "${inode}")"
-    if [[ -f "${newURI}" ]]; then
-        echo "${me}: File path ${wallURI} is incorrect. Using ${newURI} instead." >&2
-        sqlChanges="${sqlChanges}"" file_path=\"${newURI}\","
-        wallURI="${newURI}"
-    else
-        echo "${me}: Cannot find file ${file} or inode ${inode}" >&2
-        exit 5
-    fi
-fi
-
-while getopts ":a:c:df:hm:p:s:t:u:v:" opt; do
-    case "${opt}" in
-        "a")
-           comments="$(sqlite3 "${wallDB}" "SELECT user_comments FROM Wallpapers WHERE inode=${inode}")"
-           if [[ -z "${sqlChanges}" ]]; then
-               comments=","
-           fi
-           comments=",${OPTARG}"
-           sqlChanges="${sqlChanges}"" user_comments = \"${comments}\","
-           ;;
-        "d")
-            dims=($(sfp wall-dims -n -f "${wallURI}"))
-            if [[ ${dims[0]} -eq 0 || ${dims[1]} -eq 0 ]]; then
-                echo "${me}: Cannot get dimensions for ${wallURI}." >&2
-                exit 6
-            fi
-            sqlChanges="${sqlChanges}"" width = ${dims[0]}, height = ${dims[1]},"
-            ;;
-        "h")
-            cat <<EOS
-Usage: sfp ${me} OPTIONS...
+function __alter-help() {
+    cat <<EOS
+Usage: sfp ${subName} OPTIONS...
 
 Options
   -a           Add user comment (appends comma, then argument)
@@ -93,85 +35,154 @@ Options
   -u           Update user comments (use hyphen to edit existing in EDITOR)
   -v           Update the view count of the wallpaper
 EOS
-          exit 0
-          ;;
-        "m")
-          OPTIONS="centered scaled spanned zoom stretched wallpaper"
-          if [[ "${OPTARG}" == - ]]; then
-              select choice in ${OPTIONS}; do
-                  sqlChanges="${sqlChanges}"" view_mode =\"${choice}\","
-                  break
-              done
-          else
-              case ${OPTARG} in
-                  "centered"|"scaled"|"spanned"|"zoom"|"stretched"|"wallpaper")
-                      sqlChanges="${sqlChanges}"" view_mode =\"${OPTARG}\","
-                  ;;
-                  *) #Invalid view option
-                      echo "${me}: Invalid picture option ${OPTARG}" >&2
-                      exit 8
-                  ;;
-              esac
-          fi
-          ;;
-        "p")
-           sqlChanges="${sqlChanges}"" file_path = ${OPTARG},"
-          ;;
-        "s")
-           if [[ "${OPTARG}" =~ ^[1-5]$ || "${OPTARG}" == "NULL" ]]; then
-               sqlChanges="${sqlChanges}"" star_rating = ${OPTARG},"
-           else
-               echo "${me}: Invalid star rating ${OPTARG}" >&2
-               exit 10
-           fi
-          ;;
-        "t")
-           case "${OPTARG}" in
-               "0"|"false"|"off"|"f"|"no"|"F"|"unselected") sel=0 ;;
-               "1"|"true"|"on"|"t"|"yes"|"T"|"selected") sel=1 ;;
-               *) echo "${me}: Invalid selectedness ${OPTARG}" >&2
-                  exit 7
-               ;;
-           esac
-           sqlChanges="${sqlChanges}"" selected = ${sel},"
-          ;;
-        "u")
-           if [[ "${OPTARG}" == "-" ]]; then
-               tempFile="/tmp/alterWallInDB.$(date +%s).comments"
-               sqlite3 "${wallDB}" "SELECT user_comments FROM Wallpapers WHERE inode=${inode}" > ${tempFile}
-               ${EDITOR} ${tempFile}
-               comments=$(cat "${tempFile}")
-               sqlChanges="${sqlChanges}""user_comments = \"${comments}\","
-           else
-               sqlChanges="${sqlChanges}""user_comments = \"${OPTARG}\","
-           fi
-           ;;
-        "v")
-          if [[ "${OPTARG}" =~ ^[0-9]+$ ]];then
-              sqlChanges="${sqlChanges}"" view_count = ${OPTARG},"
-          else
-              echo "${me}: Cannot update view count on non-integer." >&2
-              exit 9
-          fi
-          ;;
-        \?) # Invalid option
-           echo "${me}: Invalid option -${OPTARG}" >&2
-           exit 1
-          ;;
-        :)
-           echo "${me}: Option -${OPTARG} requires an argument." >&2
-           exit 2
-          ;;
-    esac
-done
+}
 
-if [[ ! -z "${sqlChanges}" ]]; then
-    sqlStmt="UPDATE Wallpapers SET ${sqlChanges%,} WHERE inode=${inode}"
-    echo "$(date +%Y-%m-%d-%T): ${me}: Running ${sqlStmt}" >> "${logFile}"
-    sqlite3 "${wallDB}" "${sqlStmt}"
-    if [[ ${?} -ne 0 ]]; then
-        echo "${me}: Errors occurred updating ${wallURI} while running ${sqlStmt}" > >(tee -a "${logFile}" >&2)
+function __sfp-alter() {
+    source "${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf"
+    wallURI=$(sfp get-uri)
+
+    # The file needs to be asserted first, out of all the arguments
+    count=1
+    while [[ "${count}" -le "${#}" ]]; do
+        if [[ "${!count}" == "-f" ]]; then
+            # Check that the wall file is not being set multiple times
+            if [[ -z "${set}" ]]; then
+                set=true
+                count=$((count+1))
+                wallURI=${!count}
+            else
+                echo "${subName}: Wall file cannot be set twice." >&2
+                exit 3
+            fi
+        fi
+        count=$((count + 1))
+    done
+
+    #Get inode so that if /anything/ else changes we can still update
+    inode=$(sfp stats -n -f "${wallURI}" | cut -d ' ' -f 1)
+
+    if [[ "${#}" -ne 0 && -z "${inode}" ]]; then
+        echo "${subName}: Fatal error: no inode found for ${wallURI}" >&2
+        exit 4
     fi
-else
-    echo "$(date +%Y-%m-%d-%T): ${me}: No changes to make" >> "${logFile}"
-fi
+
+    # If the file path is currently wrong, find the file by inode
+    if [[ ! -f "${wallURI}" ]]; then
+        newURI="$(find "${wallDir}" -inum "${inode}")"
+        if [[ -f "${newURI}" ]]; then
+            echo "${subName}: File path ${wallURI} is incorrect. Using ${newURI} instead." >&2
+            sqlChanges="${sqlChanges}"" file_path=\"${newURI}\","
+            wallURI="${newURI}"
+        else
+            echo "${subName}: Cannot find file ${file} or inode ${inode}" >&2
+            exit 5
+        fi
+    fi
+
+    while getopts ":a:c:df:hm:p:s:t:u:v:" opt; do
+        case "${opt}" in
+            "a")
+                comments="$(sqlite3 "${wallDB}" "SELECT user_comments FROM Wallpapers WHERE inode=${inode}")"
+                if [[ -z "${sqlChanges}" ]]; then
+                    comments=","
+                fi
+                comments=",${OPTARG}"
+                sqlChanges="${sqlChanges}"" user_comments = \"${comments}\","
+                ;;
+            "d")
+                dims=($(sfp dims -n -f "${wallURI}"))
+                if [[ ${dims[0]} -eq 0 || ${dims[1]} -eq 0 ]]; then
+                    echo "${subName}: Cannot get dimensions for ${wallURI}." >&2
+                    exit 6
+                fi
+                sqlChanges="${sqlChanges}"" width = ${dims[0]}, height = ${dims[1]},"
+                ;;
+            "h")
+                __alter-help
+                exit 0
+                ;;
+            "m")
+                OPTIONS="centered scaled spanned zoom stretched wallpaper"
+                if [[ "${OPTARG}" == - ]]; then
+                    select choice in ${OPTIONS}; do
+                        sqlChanges="${sqlChanges}"" view_mode =\"${choice}\","
+                        break
+                    done
+                else
+                    case ${OPTARG} in
+                        "centered"|"scaled"|"spanned"|"zoom"|"stretched"|"wallpaper")
+                            sqlChanges="${sqlChanges}"" view_mode =\"${OPTARG}\","
+                            ;;
+                        *) #Invalid view option
+                            echo "${subName}: Invalid picture option ${OPTARG}" >&2
+                            exit 8
+                            ;;
+                    esac
+                fi
+                ;;
+            "p")
+                sqlChanges="${sqlChanges}"" file_path = ${OPTARG},"
+                ;;
+            "s")
+                if [[ "${OPTARG}" =~ ^[1-5]$ || "${OPTARG}" == "NULL" ]]; then
+                    sqlChanges="${sqlChanges}"" star_rating = ${OPTARG},"
+                else
+                    echo "${subName}: Invalid star rating ${OPTARG}" >&2
+                    exit 10
+                fi
+                ;;
+            "t")
+                case "${OPTARG}" in
+                    "0"|"false"|"off"|"f"|"no"|"F"|"unselected") sel=0 ;;
+                    "1"|"true"|"on"|"t"|"yes"|"T"|"selected") sel=1 ;;
+                    *) echo "${subName}: Invalid selectedness ${OPTARG}" >&2
+                        exit 7
+                        ;;
+                esac
+                sqlChanges="${sqlChanges}"" selected = ${sel},"
+                ;;
+            "u")
+                if [[ "${OPTARG}" == "-" ]]; then
+                    tempFile="/tmp/alterWallInDB.$(date +%s).comments"
+                    sqlite3 "${wallDB}" "SELECT user_comments FROM Wallpapers WHERE inode=${inode}" > ${tempFile}
+                    ${EDITOR} ${tempFile}
+                    comments=$(cat "${tempFile}")
+                    sqlChanges="${sqlChanges}""user_comments = \"${comments}\","
+                else
+                    sqlChanges="${sqlChanges}""user_comments = \"${OPTARG}\","
+                fi
+                ;;
+            "v")
+                if [[ "${OPTARG}" =~ ^[0-9]+$ ]];then
+                    sqlChanges="${sqlChanges}"" view_count = ${OPTARG},"
+                else
+                    echo "${subName}: Cannot update view count on non-integer." >&2
+                    exit 9
+                fi
+                ;;
+            \?) # Invalid option
+                echo "${subName}: Invalid option -${OPTARG}" >&2
+                exit 1
+                ;;
+            :)
+                echo "${subName}: Option -${OPTARG} requires an argument." >&2
+                exit 2
+                ;;
+        esac
+    done
+
+    if [[ ! -z "${sqlChanges}" ]]; then
+        sqlStmt="UPDATE Wallpapers SET ${sqlChanges%,} WHERE inode=${inode}"
+        echo "$(date +%Y-%m-%d-%T): ${subName}: Running ${sqlStmt}" >> "${logFile}"
+        sqlite3 "${wallDB}" "${sqlStmt}"
+        if [[ ${?} -ne 0 ]]; then
+            echo "${subName}: Errors occurred updating ${wallURI} while running ${sqlStmt}" > >(tee -a "${logFile}" >&2)
+        fi
+    else
+        echo "$(date +%Y-%m-%d-%T): ${subName}: No changes to make" >> "${logFile}"
+    fi
+}
+
+function sfp-alter() {
+    __sfp-alter ${*}
+}
diff --git a/bin/sfp-change-wall b/bin/sfp-change-wall
--- a/bin/sfp-change-wall
+++ b/bin/sfp-change-wall
@@ -16,13 +16,13 @@
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-me="change"
+subName="change"
 
 #Check that the file is prefixed by "file://"
 function __sfp_prefixURI() {
     pfpath="${1}"
     if [[ ! -f  "$(echo "${pfpath##*:\/\/}" | sed s/^\'// | sed s/\'$//)" ]]; then
-        echo >&2 "${me}: File \"${pfpath}\" does not exist"
+        echo >&2 "${subName}: File \"${pfpath}\" does not exist"
         exit 2
     fi
 
@@ -37,7 +37,7 @@ function __sfp-change() {
     source "${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf"
 
     if [[ ${#} -eq 0 ]]; then
-        echo >&2 "${me}: No args given. Exiting without change."
+        echo >&2 "${subName}: No args given. Exiting without change."
         exit 1
     fi
 
@@ -58,13 +58,13 @@ function __sfp-change() {
         pfpath=$(__sfp_prefixURI "${fpath}")
         DISPLAY=:0 gsettings set org.gnome.desktop.background picture-uri "${pfpath}"
     else
-        echo >&2 "${me}: Cannot read for session ${DESKTOP_SESSION}"
+        echo >&2 "${subName}: Cannot read for session ${DESKTOP_SESSION}"
         exit 3
     fi
 
-    echo "$(date +%Y-%m-%d-%T): ${me}: Wallpaper set to ${fpath}" >> ${logFile}
+    echo "$(date +%Y-%m-%d-%T): ${subName}: Wallpaper set to ${fpath}" >> ${logFile}
 }
 
 sfp-change () {
-    __sfp-change "${*}"
+    __sfp-change ${*}
 }
diff --git a/bin/sfp-dims b/bin/sfp-dims
--- a/bin/sfp-dims
+++ b/bin/sfp-dims
@@ -16,71 +16,82 @@
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-me=$(basename "${0}")
+subName=$(basename "${0}")
 
-while getopts ":f:hnr" opt; do
-    case "${opt}" in
-        f) wall=${OPTARG}
-        ;;
-        h) cat << EOS
-Usage: ${me} [OPTION]
+function __dims-help() {
+    cat << EOS
+Usage: ${subName} [OPTION]
 
     (no option)	       Print the dimensions of the wallpaper (format: width x height)
     -f                 Print the dimensions of the given wallpaper (format: width x height)
     -n                 Print the dimensions of the wallpaper without an x (format: width height)
     -h                 Display this help message
 EOS
-        exit 0
-        ;;
-        n) noX=true
-        ;;
-        r) ratio=true
-        ;;
-    esac
-done
+}
+function __sfp-dims() {
 
-# Use current wallpaper on no args
-if [[ -z "${wall}" ]]; then
-    echo "${me}: Using current wallpaper." > /dev/stderr
-    wall=$(sfp-get-uri)
-fi
+    while getopts ":f:hnr" opt; do
+        case "${opt}" in
+            f) wall=${OPTARG}
+                ;;
+            h) 
+                exit 0
+                ;;
+            n) noX=true
+                ;;
+            r) ratio=true
+                ;;
+        esac
+    done
 
-# Check file exists
-if [[ ! -f ${wall} ]]; then
-    echo "${me}: File not found  - \"${wall}\""
-    exit 1
-fi
-
-if [[ "${wall}" == *"png" ]]; then
-    info=($(file "${wall}" 2> /dev/null | sed 's/^.*PNG image data, //' | sed 's/,.*$//' | sed 's/ x//'))
-    if [[ ${?} -ne 0 ]]; then
-        echo "${me}: Invalid image file \"${wall}\""> /dev/stderr
-        exit 2
+    # Use current wallpaper on no args
+    if [[ -z "${wall}" ]]; then
+        echo "${subName}: Using current wallpaper." > /dev/stderr
+        wall=$(sfp-get-uri)
     fi
-    width=${info[0]}
-    height=${info[1]}
-elif [[ "${wall}" == *"gif" ]]; then
-    info=($(file "${wall}" 2> /dev/null | sed 's/^.*GIF image data, //' | sed 's/,.*$//' | sed 's/ x//'))
-    if [[ ${?} -ne 0 ]]; then
-        echo "${me}: Invalid image file \"${wall}\""> /dev/stderr
-        exit 3
-    fi
-    width=${info[1]}
-    height=${info[2]}
-else # JPG case
-	info=($(file -P name=50 "${wall}" | rev | cut -d, -f 2 | tr -d '[[:space:]]' | rev | sed 's/x/ /' ))
-    if [[ ${?} -ne 0 ]]; then
-        echo "${me}: Invalid image file \"${wall}\""> /dev/stderr
-        exit 4
-    fi
-    width=${info[0]}
-    height=${info[1]}
-fi
 
-if [[ ${noX} ]]; then
-    echo ${width} ${height}
-elif [[ ${ratio} ]]; then
-    echo "${width} / ${height}" | bc -l | sed 's,\.\([0-9][0-9]\).*,.\1,'
-else
-    echo "${width} x ${height}"
-fi
+    # Check file exists
+    if [[ ! -f ${wall} ]]; then
+        echo "${subName}: File not found  - \"${wall}\""
+        exit 1
+    fi
+
+    if [[ "${wall}" == *"png" ]]; then
+        info=($(file "${wall}" 2> /dev/null | sed 's/^.*PNG image data, //' | sed 's/,.*$//' | sed 's/ x//'))
+        if [[ ${?} -ne 0 ]]; then
+            echo "${subName}: Invalid image file \"${wall}\""> /dev/stderr
+            exit 2
+        fi
+        width=${info[0]}
+        height=${info[1]}
+    elif [[ "${wall}" == *"gif" ]]; then
+        info=($(file "${wall}" 2> /dev/null | sed 's/^.*GIF image data, //' | sed 's/,.*$//' | sed 's/ x//'))
+        if [[ ${?} -ne 0 ]]; then
+            echo "${subName}: Invalid image file \"${wall}\""> /dev/stderr
+            exit 3
+        fi
+        width=${info[1]}
+        height=${info[2]}
+    else # JPG case
+        info=($(file -P name=50 "${wall}" | rev | cut -d, -f 2 | tr -d '[[:space:]]' | rev | sed 's/x/ /' ))
+        if [[ ${?} -ne 0 ]]; then
+            echo "${subName}: Invalid image file \"${wall}\""> /dev/stderr
+            exit 4
+        fi
+        width=${info[0]}
+        height=${info[1]}
+    fi
+
+    if [[ ${noX} ]]; then
+        echo ${width} ${height}
+    elif [[ ${ratio} ]]; then
+        echo "${width} / ${height}" | bc -l | sed 's,\.\([0-9][0-9]\).*,.\1,'
+    else
+        echo "${width} x ${height}"
+    fi
+}
+
+function sfp-dims() {
+    __sfp-dims ${*}
+}
+
diff --git a/bin/sfp-get-sql-stmt b/bin/sfp-get-sql-stmt
--- a/bin/sfp-get-sql-stmt
+++ b/bin/sfp-get-sql-stmt
@@ -16,28 +16,10 @@
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-me=$(basename "${0}")
-
-# Check args
-if [[ "${#}" -eq 0 ]]; then
-    echo >&2 "${me}: Missing args"
-    exit 1
-fi
-
-# Setup vars
-string=""
-source "${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf"
-
-isSelected() {
-    if [[ "${file}" == "*/Unselected/*" ]]; then
-        echo 0
-    else
-        echo 1
-    fi
-}
+subName="get-sql-stmt"
 
 # Function: Compile an SQL Insert statement
-buildInsert(){
+function __sfp-get-sql-stmt-buildInsert() {
     file="${1}"
 
     # Insert syntax
@@ -49,9 +31,9 @@ buildInsert(){
     # Hash
     string="${string}""\"$(sha1sum "${file}" | cut -d' ' -f 1)\", "
     # Dimensions
-    dims=$(sfp wall-dims -n -f "${file}")
+    dims=$(sfp dims -n -f "${file}")
     if [[ ${?} -ne 0 ]]; then
-        echo "${me}: Failed to build insert for ${1}" > /dev/stderr
+        echo "${subName}: Failed to build insert for ${1}" > /dev/stderr
         exit 2
     fi
     string="${string}""$(echo ${dims} | tr -d '\n' | sed 's/ /, /'), "
@@ -60,9 +42,10 @@ buildInsert(){
 
     echo ${string}
 }
+export -f __sfp-get-sql-stmt-buildInsert
 
 # Function: Compile an SQL Update statement
-buildUpdate() {
+function __sfp-get-sql-stmt-buildUpdate() {
     inode="${1}"
     file="$(find "${wallDir}" -inum "${inode}")"
     if [[ -f "${file}" ]]; then # and the argument is a file
@@ -71,7 +54,7 @@ buildUpdate() {
         # File path
         string="${string}""file_path = \"${file}\", "
         # Dimensions
-        string="${string}""width = $(sfp wall-dims -n -f "${file}" | tr -d '\n' | sed 's/ /, height = /'), "
+        string="${string}""width = $(sfp dims -n -f "${file}" | tr -d '\n' | sed 's/ /, height = /'), "
         # Selectedness
         string="${string}""selected = $(isSelected "${file}") "
         # WHERE syntax
@@ -81,24 +64,49 @@ buildUpdate() {
     fi
     echo ${string}
 }
+export -f __sfp-get-sql-stmt-buildUpdate
 
-if [[ "${1}" =~ ^[0-9]+$ ]]; then # Argument is an inode
-    inode="${1}"
-    # Find file
-    file=$(readlink -f "$(find ${wallDir} -inum ${inode})")
-
-    if [[ -f "${file}" ]]; then # No entry, but file exists
-        string="$(buildInsert "${file}")"
-    else
-        echo "${me}: File not found for inode ${1}" > /dev/stderr
+function __sfp-get-sql-stmt() {
+    # Check args
+    if [[ "${#}" -eq 0 ]]; then
+        echo >&2 "${subName}: Missing args"
+        exit 1
     fi
-else # Argument is not numerical
-    file="${1}"
-    if [[ -f "${file}" ]]; then
-        string="$(buildInsert "${file}")"
-    fi
-fi
 
-if [[ ! -z "${string}" ]]; then
-    echo ${string}
-fi
+    # Setup vars
+    string=""
+    source "${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf"
+
+    function isSelected() (
+        if [[ "${file}" == "*/Unselected/*" ]]; then
+            echo 0
+        else
+            echo 1
+        fi
+    )
+
+    if [[ "${1}" =~ ^[0-9]+$ ]]; then # Argument is an inode
+        inode="${1}"
+        # Find file
+        file=$(readlink -f "$(find ${wallDir} -inum ${inode})")
+
+        if [[ -f "${file}" ]]; then # No entry, but file exists
+            string="$(__sfp-get-sql-stmt-buildInsert "${file}")"
+        else
+            echo "${subName}: File not found for inode ${1}" > /dev/stderr
+        fi
+    else # Argument is not numerical
+        file="${1}"
+        if [[ -f "${file}" ]]; then
+            string="$(__sfp-get-sql-stmt-buildInsert "${file}")"
+        fi
+    fi
+
+    if [[ ! -z "${string}" ]]; then
+        echo ${string}
+    fi
+}
+
+function sfp-get-sql-stmt() {
+    __sfp-get-sql-stmt ${*}
+}
diff --git a/bin/sfp-get-uri b/bin/sfp-get-uri
--- a/bin/sfp-get-uri
+++ b/bin/sfp-get-uri
@@ -16,23 +16,30 @@
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# Get background
-if [ $(pgrep cinnamon | wc -l) -ne 0 ]; then
-    url=$(gsettings get org.cinnamon.desktop.background picture-uri | cut -c9- | rev | cut -c2- | rev)
-elif [ $(pgrep mate-session | wc -l) -ne 0 ]; then
-    url=$(gsettings get org.mate.background picture-filename | cut -c2- | rev | cut -c2- | rev)
-elif [ $(pgrep gnome | wc -l) -ne 0 ]; then
-    export $(dbus-launch)
-    urlUncut=$(gsettings get org.gnome.desktop.background picture-uri)
-    if [[ "${urlUncut}" == "'file://"* || "${urlUncut}" == \"file://* ]]; then
-        url=$(echo "${urlUncut}" | cut -c9- | rev | cut -c2- | rev)
-    elif [[ "${urlUncut}" == \'* ]]; then
-        url="$(echo "${urlUncut}" | cut -c2- | rev | cut -c2- | rev)"
+subName="get-uri"
+function __sfp-get-uri() {
+    # Get background
+    if [ $(pgrep cinnamon | wc -l) -ne 0 ]; then
+        url=$(gsettings get org.cinnamon.desktop.background picture-uri | cut -c9- | rev | cut -c2- | rev)
+    elif [ $(pgrep mate-session | wc -l) -ne 0 ]; then
+        url=$(gsettings get org.mate.background picture-filename | cut -c2- | rev | cut -c2- | rev)
+    elif [ $(pgrep gnome | wc -l) -ne 0 ]; then
+        export $(dbus-launch)
+        urlUncut=$(gsettings get org.gnome.desktop.background picture-uri)
+        if [[ "${urlUncut}" == "'file://"* || "${urlUncut}" == \"file://* ]]; then
+            url=$(echo "${urlUncut}" | cut -c9- | rev | cut -c2- | rev)
+        elif [[ "${urlUncut}" == \'* ]]; then
+            url="$(echo "${urlUncut}" | cut -c2- | rev | cut -c2- | rev)"
+        else
+            url="${urlUncut}"
+        fi
     else
-        url="${urlUncut}"
+        echo >&2 "${subName}: Cannot read for session ${DESKTOP_SESSION}"
+        exit 2
     fi
-else
-    echo >&2 "Cannot read for session ${DESKTOP_SESSION}"
-    exit 2
-fi
-echo "${url}"
+    echo "${url}"
+}
+
+function sfp-get-uri() {
+    __sfp-get-uri ${*}
+}
diff --git a/bin/sfp-init-db b/bin/sfp-init-db
--- a/bin/sfp-init-db
+++ b/bin/sfp-init-db
@@ -16,32 +16,33 @@
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-me="$(basename "${0}")"
-confDir="$(dirname "${0}")"/../conf
+subName="init-db"
+function __sfp-init-db() {
+    confDir="$(dirname "${0}")"/../conf
 
-if [[ -z "${XDG_CONFIG_HOME}" || ! -d "${XDG_CONFIG_HOME}" ]]; then
-    echo "Cannot install without XDG_CONFIG_HOME set to a valid directory"
-    exit 4
-fi
+    if [[ -z "${XDG_CONFIG_HOME}" || ! -d "${XDG_CONFIG_HOME}" ]]; then
+        echo "Cannot install without XDG_CONFIG_HOME set to a valid directory"
+        exit 4
+    fi
 
-install -Dm 644 "${confDir}/shufflepaper.conf" "${XDG_CONFIG_HOME}/shufflepaper"
-# Source shufflepaper variables
-source ${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf
+    install -Dm 644 "${confDir}/shufflepaper.conf" "${XDG_CONFIG_HOME}/shufflepaper"
+    # Source shufflepaper variables
+    source ${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf
 
-# Ensure data directory exists
-if [[ ! -d "${dataDir}" ]]; then
-    mkdir -p "${dataDir}"
-fi
+    # Ensure data directory exists
+    if [[ ! -d "${dataDir}" ]]; then
+        mkdir -p "${dataDir}"
+    fi
 
-# Set up database
-if [[ ! -f "${wallDB}" ]]; then
-    sqlite3 "${wallsDB}" < "${confDir}"/dbSetup.sql
-else
-    echo "${me}: Error - walls.db exists at ${wallsDB}. Script will not install in place of existing files"
-fi
+    # Set up database
+    if [[ ! -f "${wallDB}" ]]; then
+        sqlite3 "${wallsDB}" < "${confDir}"/dbSetup.sql
+    else
+        echo "${subName}: Error - walls.db exists at ${wallsDB}. Script will not install in place of existing files"
+    fi
 
-if [[ ! -f "${userConf}" ]]; then
-    cat > "${userConf}" << EOS
+    if [[ ! -f "${userConf}" ]]; then
+        cat > "${userConf}" << EOS
 #!/usr/bin/env bash
 # user.conf
 # Update your wallpaper folder and random selection qualifiers here
@@ -50,6 +51,11 @@ wallDir=\${HOME}/Pictures/Wallpapers
 whereClause='selected=1'
 last_updated=
 EOS
-else
-    echo "${me}: Error - user configuration exists at ${userConf}. Script will not install in place of existing files"
-fi
+    else
+        echo "${subName}: Error - user configuration exists at ${userConf}. Script will not install in place of existing files"
+    fi
+}
+
+function sfp-init-db() {
+    __sfp-init-db ${*}
+}
diff --git a/bin/sfp-miner b/bin/sfp-miner
--- a/bin/sfp-miner
+++ b/bin/sfp-miner
@@ -17,123 +17,129 @@
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# Vars
-me="$(basename "${0}")"
-source "${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf"
+subName="miner"
 
-diffFile=/tmp/inodeList.diff
-inodeList="${dataDir}"/inode.list
-tempList="/tmp/inode.list"
-txnFile=/tmp/"${me}".txn
+function __sfp-miner() {
+    source "${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf"
 
-# Ensure data directory exists
-if [[ ! -d "${dataDir}" ]]; then
-    sfp init-db
-fi
+    diffFile=/tmp/inodeList.diff
+    inodeList="${dataDir}"/inode.list
+    tempList="/tmp/inode.list"
+    txnFile=/tmp/"${subName}".txn
 
-# Create inode list from database
-sqlite3 "${wallDB}" "SELECT inode FROM Wallpapers;" | sort > "${inodeList}"
-
-# Update all wallpapers that have been modified since last run
-time=$(date +%s)
-timeSince=$(( (${last_updated} - ${time}) / 86400 ))
-while read line; do
-    # Skip empty lines
-    if [[ -z "${line}" ]]; then
-        continue
+    # Ensure data directory exists
+    if [[ ! -d "${dataDir}" ]]; then
+        sfp init-db
     fi
-    # If the inode is not present in the database, skip it, it will be added later
-    if ! grep "${line}" "${inodeList}" > /dev/null; then
-        continue
-    fi
-    file=$(sqlite3 "${HOME}/.local/share/shufflepaper/walls.db" 'SELECT file_path FROM Wallpapers WHERE inode ='"${line}")
-    # Updating dims also checks file path
-    sfp alter -d -f "${file}"
-done <<<"$(find "${wallDir}" \( -name "*jpg" -o -name "*png" \) -mtime "${timeSince}" -printf "%i\n" | sort)"
-# When finished update lastUpdated time
-sed -i 's/^\(last_updated=\).*$/\1'"$(date +%s)"'/' "${userConf}"
 
-# Empty transaction file
-echo -n > "${txnFile}"
+    # Create inode list from database
+    sqlite3 "${wallDB}" "SELECT inode FROM Wallpapers;" | sort > "${inodeList}"
 
-# Create new list from files
-find "${wallDir}" \( -name "*jpg" -o -name "*png" \) -printf "%i\n" | sort > "${tempList}"
+    # Update all wallpapers that have been modified since last run
+    time=$(date +%s)
+    timeSince=$(( (${last_updated} - ${time}) / 86400 ))
+    while read line; do
+        # Skip empty lines
+        if [[ -z "${line}" ]]; then
+            continue
+        fi
+        # If the inode is not present in the database, skip it, it will be added later
+        if ! grep "${line}" "${inodeList}" > /dev/null; then
+            continue
+        fi
+        file=$(sqlite3 "${HOME}/.local/share/shufflepaper/walls.db" 'SELECT file_path FROM Wallpapers WHERE inode ='"${line}")
+        # Updating dims also checks file path
+        sfp alter -d -f "${file}"
+    done <<<"$(find "${wallDir}" \( -name "*jpg" -o -name "*png" \) -mtime "${timeSince}" -printf "%i\n" | sort)"
+    # When finished update lastUpdated time
+    sed -i 's/^\(last_updated=\).*$/\1'"$(date +%s)"'/' "${userConf}"
 
-# If an inode list exists compare with it
-if [[ -f "${inodeList}" ]]; then
-    change=false
-    diff --speed-large-files "${inodeList}" "${tempList}" | grep [\>\<] > "${diffFile}"
+    # Empty transaction file
+    echo -n > "${txnFile}"
 
-    # Wallpaper removed condition
-    if grep \< "${diffFile}" > /dev/null 2> /dev/null; then
-        numRemoved=$(grep \< "${diffFile}" | wc -l)
-        count=0
+    # Create new list from files
+    find "${wallDir}" \( -name "*jpg" -o -name "*png" \) -printf "%i\n" | sort > "${tempList}"
+
+    # If an inode list exists compare with it
+    if [[ -f "${inodeList}" ]]; then
+        change=false
+        diff --speed-large-files "${inodeList}" "${tempList}" | grep [\>\<] > "${diffFile}"
+
+        # Wallpaper removed condition
+        if grep \< "${diffFile}" > /dev/null 2> /dev/null; then
+            numRemoved=$(grep \< "${diffFile}" | wc -l)
+            count=0
+            while read line; do
+                # Compile SQL statement
+                string="DELETE FROM Wallpapers WHERE (inode = \"${line}\");"
+                echo ${string} >> "${txnFile}"
+                count=$((${count} + 1))
+                echo -ne "Removing ${count} out of ${numRemoved}\r"
+            done <<< "$(grep \< ${diffFile} | sed 's/^< //')"
+            echo
+            change=true
+        fi
+
+        if [[ -s "${txnFile}" ]]; then
+            sqlite3 "${wallDB}" < "${txnFile}"
+            echo > "${txnFile}"
+            # If deletion fails, don't press on -- user needs to work it out
+            if [[ ${?} -ne 0 ]]; then
+                echo "${subName}: $(date +%D.%T) Failed to execute transaction" | tee -a ${logFile} >> /dev/stderr
+                exit 1
+            fi
+        fi
+
+        # Wallpaper added condition
+        if grep \> "${diffFile}"> /dev/null 2> /dev/null; then
+            numRemoved=$(grep \> "${diffFile}" | wc -l)
+            count=0
+            while read line; do
+                sfp get-sql-stmt "${line}" >> "${txnFile}"
+                count=$((${count} + 1))
+                echo -ne "Compiling transaction (${count} of ${numRemoved})\r"
+            done <<< "$(grep \> ${diffFile} | sed 's/^> //')"
+            echo
+            change=true
+        fi
+
+        rm "${diffFile}"
+
+        # Update backgrounds with modification newer than the wallDB
         while read line; do
-             # Compile SQL statement
-             string="DELETE FROM Wallpapers WHERE (inode = \"${line}\");"
-             echo ${string} >> "${txnFile}"
-             count=$((${count} + 1))
-             echo -ne "Removing ${count} out of ${numRemoved}\r"
-        done <<< "$(grep \< ${diffFile} | sed 's/^< //')"
-        echo
-        change=true
+            change=true
+            sfp get-sql-stmt "${line}" >> "${txnFile}"
+        done <<< "$(find "${wallDir}" -newer "${wallDB}" -type f \( -name "*png" -o -name "*jpg" \) -printf "%i\n" | sort)"
+
+        if ! "${change}"; then
+            echo "${subName}: $(date +%D.%T) No changes to wallpapers detected." >> ${logFile}
+        fi
+
+    else # If no inode list exists, add all wallpapers
+        while read line; do
+            sfp get-sql-stmt "${line}" >> "${txnFile}"
+        done <<< "$(cat ${tempList})"
     fi
 
     if [[ -s "${txnFile}" ]]; then
+        echo "Running update transaction"
         sqlite3 "${wallDB}" < "${txnFile}"
-        echo > "${txnFile}"
-        # If deletion fails, don't press on -- user needs to work it out
+
+        # On fail: warn and exit
         if [[ ${?} -ne 0 ]]; then
-            echo "${me}: $(date +%D.%T) Failed to execute transaction" | tee -a ${logFile} >> /dev/stderr
+            echo "${subName}: $(date +%D.%T) Failed to execute transaction" | tee -a ${logFile} >> /dev/stderr
             exit 1
+        else
+            echo "Transaction complete."
         fi
-    fi
-
-    # Wallpaper added condition
-    if grep \> "${diffFile}"> /dev/null 2> /dev/null; then
-        numRemoved=$(grep \> "${diffFile}" | wc -l)
-        count=0
-        while read line; do
-             sfp get-sql-stmt "${line}" >> "${txnFile}"
-             count=$((${count} + 1))
-             echo -ne "Compiling transaction (${count} of ${numRemoved})\r"
-        done <<< "$(grep \> ${diffFile} | sed 's/^> //')"
-        echo
-        change=true
-    fi
-
-    rm "${diffFile}"
-
-    # Update backgrounds with modification newer than the wallDB
-    while read line; do
-        change=true
-        sfp get-sql-stmt "${line}" >> "${txnFile}"
-    done <<< "$(find "${wallDir}" -newer "${wallDB}" -type f \( -name "*png" -o -name "*jpg" \) -printf "%i\n" | sort)"
-
-    if ! "${change}"; then
-        echo "${me}: $(date +%D.%T) No changes to wallpapers detected." >> ${logFile}
-    fi
-
-else # If no inode list exists, add all wallpapers
-    while read line; do
-        sfp get-sql-stmt "${line}" >> "${txnFile}"
-    done <<< "$(cat ${tempList})"
-fi
-
-if [[ -s "${txnFile}" ]]; then
-    echo "Running update transaction"
-    sqlite3 "${wallDB}" < "${txnFile}"
-
-    # On fail: warn and exit
-    if [[ ${?} -ne 0 ]]; then
-        echo "${me}: $(date +%D.%T) Failed to execute transaction" | tee -a ${logFile} >> /dev/stderr
-        exit 1
     else
-        echo "Transaction complete."
+        echo "Nothing to do."
     fi
-else
-    echo "Nothing to do."
-fi
 
-rm "${txnFile}"
-exit 0
+    rm "${txnFile}"
+    exit 0
+}
+
+function sfp-miner() {
+    __sfp-miner ${*}
+}
diff --git a/bin/sfp-option b/bin/sfp-option
--- a/bin/sfp-option
+++ b/bin/sfp-option
@@ -16,12 +16,12 @@
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-me="$(basename "${0}")"
+subName="option"
 OPTIONS="centered scaled spanned zoom stretched wallpaper"
 
-help() {
+function __sfp-option-help() {
     cat << EOS
-Usage: ${me} [OPTIONS...] <ARGUMENT>
+Usage: ${subName} [OPTIONS...] <ARGUMENT>
     -h        Print this help message and exit
     -n        No update of wallpaper in DB
 Argument can be one of: ${OPTIONS}
@@ -29,33 +29,39 @@ EOS
     exit 0
 }
 
-if [[ ${#} -eq 0 ]]; then
-    help
-fi
+function __sfp-option() {
+    if [[ ${#} -eq 0 ]]; then
+        __sfp-option-help
+    fi
 
-while getopts "hn" opt; do
-    case "${opt}" in
-        "h")
-            help
+    while getopts "hn" opt; do
+        case "${opt}" in
+            "h")
+                __sfp-option-help
+                ;;
+            "n")
+                noUpdate=1
+                ;;
+        esac
+        shift
+    done
+
+    arg=${1}
+    case "${arg}" in
+        "centered"|"scaled"|"spanned"|"zoom"|"stretched"|"wallpaper")
+            export $(dbus-launch)
+            DISPLAY=:0 gsettings set org.gnome.desktop.background picture-options "${arg}"
+            if [[ -z "${noUpdate}" ]]; then
+                sfp alter -m "${arg}"
+            fi
             ;;
-        "n")
-            noUpdate=1
+        *) #Invalid view option
+            echo "${subName}: Invalid argument - ${arg}" >&2
+            exit 1
             ;;
     esac
-    shift
-done
+}
 
-arg=${1}
-case "${arg}" in
-    "centered"|"scaled"|"spanned"|"zoom"|"stretched"|"wallpaper")
-        export $(dbus-launch)
-        DISPLAY=:0 gsettings set org.gnome.desktop.background picture-options "${arg}"
-        if [[ -z "${noUpdate}" ]]; then
-            "$(dirname $(readlink -f "${0}"))/sfp-alter" -m "${arg}"
-        fi
-    ;;
-    *) #Invalid view option
-        echo "${me}: Invalid argument - ${arg}" >&2
-        exit 1
-    ;;
-esac
+function sfp-option {
+    __sfp-option ${*}
+}
diff --git a/bin/sfp-remove b/bin/sfp-remove
--- a/bin/sfp-remove
+++ b/bin/sfp-remove
@@ -16,32 +16,38 @@
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# Check args
-if [[ ${#} -eq 0 ]]; then
-    echo "${me}: Missing argument. An inode or file path is required."
-    exit 1
-fi
+function __sfp-remove() {
+    # Check args
+    if [[ ${#} -eq 0 ]]; then
+        echo "${me}: Missing argument. An inode or file path is required."
+        exit 1
+    fi
 
-# Setup vars
-source "${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf"
-file="$(readlink -f "${1}")"
-me=$(basename "${0}")
+    # Setup vars
+    source "${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf"
+    file="$(readlink -f "${1}")"
+    me=$(basename "${0}")
 
-# Compile SQL statement
-string="DELETE FROM Wallpapers WHERE ("
+    # Compile SQL statement
+    string="DELETE FROM Wallpapers WHERE ("
 
-# Match inode or file path
-if [[ ${1} =~ ^[0-9]+$ ]]; then
-    string="${string}""inode = \"${1}\");"
-else
-    string="${string}""file_path = \"${file}\");"
-fi
+    # Match inode or file path
+    if [[ ${1} =~ ^[0-9]+$ ]]; then
+        string="${string}""inode = \"${1}\");"
+    else
+        string="${string}""file_path = \"${file}\");"
+    fi
 
-# Run SQL command
-sqlite3 "${wallDB}" "${string}"
+    # Run SQL command
+    sqlite3 "${wallDB}" "${string}"
 
-# Report any errors
-if [[ ${?} -ne 0 ]]; then
-    echo "${me}: Failed to remove wallpaper using command: ${string}"
-    exit 2
-fi
+    # Report any errors
+    if [[ ${?} -ne 0 ]]; then
+        echo "${me}: Failed to remove wallpaper using command: ${string}"
+        exit 2
+    fi
+}
+
+function sfp-remove() {
+    __sfp-remove ${*}
+}
diff --git a/bin/sfp-stats b/bin/sfp-stats
--- a/bin/sfp-stats
+++ b/bin/sfp-stats
@@ -17,33 +17,15 @@
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-me=$(basename "${0}")
-source "${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf"
+subName="stats"
 
-wallURI=$(sfp get-uri)
-while getopts ":df:hn" opt; do
-    case "${opt}" in
-        "d") delimiter=true
-           ;;
-        "f") wallURI="$(readlink -f "${OPTARG}")"
-           ;;
-        "h") cat <<EOS
-Usage: ${me} [OPTIONS]
+function __sfp-stats-readDB() {
+    if [[ ${#} -eq 0 || "${1}" == "" ]]; then
+        wallURI="$(sfp get-uri)"
+    else
+        wallURI="${1}"
+    fi
 
-Options:
-    -d         Print with pipe (|) delimiter
-    -f         Use the given file instead of the current wallpaper
-    -h         Print this help
-    -n         Do not print the header column line
-EOS
-              exit 0
-           ;;
-        "n") noheader=true
-           ;;
-    esac
-done
-
-findWall() {
     if [[ "$(sqlite3 "${wallDB}" 'SELECT count(*) FROM Wallpapers WHERE file_path="'"${wallURI}"'"')" -eq 0 ]]; then
         if [[ ! -f "${wallURI}" ]]; then
             # Wall does not exist.
@@ -57,7 +39,7 @@ findWall() {
         fi
         result="$(sqlite3 "${wallDB}" "SELECT * FROM Wallpapers WHERE inode=${inode}")"
         if [[ -z "${result}" ]]; then
-            echo "${me}: Error finding wallpaper"
+            echo "${subName}: Error finding wallpaper"
             exit 1
         fi
     else
@@ -69,15 +51,51 @@ findWall() {
     fi
     echo ${result}
 }
+export -f __sfp-stats-readDB
 
-output="$(findWall)"
-ret=${?}
-if [[ "${ret}" -eq 0 ]]; then
-    if [[ -z "${delimiter}" ]]; then
-        echo "${output}" | column -s\| -t
+
+function __sfp-stats-help() {
+    cat <<EOS
+Usage: ${subName} [OPTIONS]
+
+Options:
+    -d         Print with pipe (|) delimiter
+    -f         Use the given file instead of the current wallpaper
+    -h         Print this help
+    -n         Do not print the header column line
+EOS
+}
+
+function __sfp-stats() {
+    source "${XDG_CONFIG_HOME}/shufflepaper/shufflepaper.conf"
+
+    while getopts ":df:hn" opt; do
+        case "${opt}" in
+            "d") delimiter=true
+                ;;
+            "f") wallArg="$(readlink -f "${OPTARG}")"
+                ;;
+            "h") 
+                __sfp-stats-help
+                exit 0
+                ;;
+            "n") noheader=true
+                ;;
+        esac
+    done
+    output="$(__sfp-stats-readDB "${wallArg}")"
+    ret=${?}
+    if [[ "${ret}" -eq 0 ]]; then
+        if [[ -z "${delimiter}" ]]; then
+            echo "${output}" | column -s\| -t
+        else
+            echo "${output}"
+        fi
     else
-        echo "${output}"
+        exit "${ret}"
     fi
-else
-    exit "${ret}"
-fi
+}
+
+function sfp-stats() {
+    __sfp-stats ${*}
+}
