Begin using clean test environments

diff --git a/t/sfp-display b/t/sfp-display
--- a/t/sfp-display
+++ b/t/sfp-display
@@ -1,14 +1,19 @@
-#!/usr/bin/env bash
+#!/usr/bin/env -S -i bash
+
+test -f "${1}" && source "${1}" || echo "Could not source test environment" 
+
+uriTestPass="valid-uri"
+optTestPass="options received"
 
 # gsettings interceptor
 function gsettings() {
-    if [[ "${1}" == "set" ]]; then
-        if [[ "${2}" == "org.gnome.desktop.background" ]]; then
-            if [[ "${3}" == "picture-uri" ]]; then
-                if [[ -f "${4/file:\/\//}" ]]; then
-                    echo valid-uri
-                fi
-            fi
+    if [[ "${3}" == "picture-uri" ]]; then
+        if [[ -f "${4/file:\/\//}" ]]; then
+            echo
+        fi
+    elif [[ "${3}" == "picture-opions" ]]; then
+        if [[ ! -z "${4}" ]]; then
+            echo ${optTestPass}
         fi
     fi
 }
@@ -16,7 +21,7 @@ export -f gsettings
 
 # dbus-launch interceptor
 function dbus-launch(){
-    echo dbus-launch called
+    echo "DBUS_LAUNCH=TEST"
 }
 export -f dbus-launch
 
@@ -24,4 +29,6 @@ export -f dbus-launch
 testjpg="/tmp/sfp-test/fake.jpg"
 dd if=/dev/urandom of="${testjpg}" bs=512 count=2 2> /dev/null
 
-bash -c "sfp display \"${testjpg}\"" | grep valid-uri > /dev/null
+bash -c "sfp display \"${testjpg}\"" | grep "${uriTestPass}" > /dev/null
+
+bash -c "sfp display -o zoom" | grep "${optTestPass}" > /dev/null
